-- Seed restaurants data
INSERT INTO restaurants (name, cuisine_type, address, city, country, latitude, longitude, rating, review_count, price_range, description, features, menu, phone, website, opening_hours, images) VALUES
('Le Bernardin', 'French Seafood', '155 West 51st Street, New York, NY 10019', 'New York', 'United States', 40.7614, -73.9776, 4.8, 2847, '$$$$', 'Elegant French seafood restaurant with impeccable service and world-class cuisine', '["Fine Dining", "Reservations Required", "Wine Pairing", "Private Dining"]', '[{"category": "Appetizers", "items": ["Tuna Tartare", "Oyster Selection", "Lobster Bisque"]}, {"category": "Main Courses", "items": ["Black Bass", "Halibut", "Lobster Thermidor"]}]', '+1 (212) 554-1515', 'le-bernardin.com', '{"monday": "Closed", "tuesday": "5:30 PM - 10:30 PM", "wednesday": "5:30 PM - 10:30 PM"}', '["/restaurant-fine-dining.png"]'),

('Nobu Malibu', 'Japanese', '22706 Pacific Coast Highway, Malibu, CA 90265', 'Los Angeles', 'United States', 34.0259, -118.7798, 4.6, 1923, '$$$', 'Oceanfront Japanese restaurant with innovative sushi and spectacular Pacific views', '["Ocean View", "Sushi Bar", "Sake Selection", "Outdoor Seating"]', '[{"category": "Sushi", "items": ["Yellowtail Jalapeño", "Black Cod Miso", "Toro Tartare"]}, {"category": "Hot Dishes", "items": ["Miso Glazed Cod", "Wagyu Beef", "Rock Shrimp Tempura"]}]', '+1 (310) 317-9140', 'noburestaurants.com', '{"daily": "5:00 PM - 11:00 PM"}', '["/restaurant-japanese.png"]'),

('Osteria Francescana', 'Italian', 'Via Stella 22, 41121 Modena, Italy', 'Modena', 'Italy', 44.6471, 10.9252, 4.9, 1456, '$$$$', 'Three Michelin-starred Italian restaurant showcasing the finest Emilian cuisine', '["Michelin Stars", "Wine Cellar", "Tasting Menu", "Chef''s Table"]', '[{"category": "Antipasti", "items": ["Tortellini in Brodo", "Parmigiano Reggiano", "Prosciutto di Parma"]}, {"category": "Primi", "items": ["Risotto Amarone", "Tagliatelle al Ragù", "Cappelletti"]}]', '+39 059 210118', 'osteriafrancescana.it', '{"tuesday": "7:30 PM - 11:00 PM", "wednesday": "7:30 PM - 11:00 PM"}', '["/restaurant-italian.png"]'),

('Sketch', 'Modern European', '9 Conduit St, London W1S 2XG, UK', 'London', 'United Kingdom', 51.5138, -0.1426, 4.4, 3421, '$$$', 'Avant-garde restaurant with innovative cuisine and artistic interior design', '["Artistic Interior", "Afternoon Tea", "Cocktail Bar", "Private Dining"]', '[{"category": "Starters", "items": ["Foie Gras", "Caviar Selection", "Truffle Soup"]}, {"category": "Mains", "items": ["Beef Wellington", "Sea Bass", "Duck Confit"]}]', '+44 20 7659 4500', 'sketch.london', '{"daily": "12:00 PM - 2:00 AM"}', '["/restaurant-fine-dining.png"]')
ON CONFLICT DO NOTHING;

-- Seed places/attractions data
INSERT INTO places (name, category, address, city, country, latitude, longitude, rating, review_count, description, highlights, features, opening_hours, ticket_price, duration_hours, best_time_to_visit, how_to_get_there, images, website) VALUES
('Eiffel Tower', 'Attraction', 'Champ de Mars, 5 Avenue Anatole France, 75007 Paris, France', 'Paris', 'France', 48.8584, 2.2945, 4.6, 89234, 'Iconic iron lattice tower and symbol of Paris, offering breathtaking views of the city', '["Panoramic city views", "Historic architecture", "Evening light show", "Multiple viewing levels"]', '["Skip the Line", "Audio Guide", "Photography Allowed", "Gift Shop"]', '{"daily": "9:30 AM - 11:45 PM"}', 29.00, 2.5, 'Early morning or sunset for best photos and fewer crowds', 'Metro Line 6 (Bir-Hakeim), Line 9 (Trocadéro), RER C (Champ de Mars)', '["/eiffel-tower.png"]', 'toureiffel.paris'),

('Central Park', 'Outdoor Activity', 'New York, NY 10024, United States', 'New York', 'United States', 40.7829, -73.9654, 4.7, 45678, 'Massive urban park in Manhattan offering green spaces, lakes, and recreational activities', '["Bethesda Fountain", "Strawberry Fields", "Central Park Zoo", "Bow Bridge"]', '["Family Friendly", "Free Entry", "Bike Rentals", "Guided Tours"]', '{"daily": "6:00 AM - 1:00 AM"}', 0.00, 4.0, 'Spring and fall for pleasant weather and beautiful foliage', 'Multiple subway stations around the park perimeter', '["/central-park.png"]', 'centralparknyc.org'),

('Louvre Museum', 'Museum', 'Rue de Rivoli, 75001 Paris, France', 'Paris', 'France', 48.8606, 2.3376, 4.5, 67890, 'World''s largest art museum housing masterpieces including the Mona Lisa and Venus de Milo', '["Mona Lisa", "Venus de Milo", "Winged Victory", "Egyptian Antiquities"]', '["Audio Guide", "Skip the Line", "Wheelchair Accessible", "Museum Shop"]', '{"monday": "Closed", "tuesday": "Closed", "wednesday": "9:00 AM - 6:00 PM", "thursday": "9:00 AM - 9:45 PM"}', 17.00, 4.5, 'Wednesday evenings or early morning to avoid crowds', 'Metro Line 1 (Palais-Royal), Line 7 (Pont Neuf)', '["/louvre-museum.png"]', 'louvre.fr'),

('Tokyo Skytree', 'Attraction', '1 Chome-1-2 Oshiage, Sumida City, Tokyo 131-0045, Japan', 'Tokyo', 'Japan', 35.7101, 139.8107, 4.3, 23456, 'World''s second tallest structure offering spectacular views of Tokyo and Mount Fuji', '["360-degree city views", "Mount Fuji views", "Shopping complex", "Aquarium"]', '["Fast Track Entry", "Audio Guide", "Photography Allowed", "Restaurant"]', '{"daily": "8:00 AM - 10:00 PM"}', 25.00, 2.0, 'Clear days for Mount Fuji views, sunset for city lights', 'Tokyo Skytree Station (Tobu Skytree Line), Oshiage Station (Asakusa Line)', '["/tokyo-skytree.png"]', 'tokyo-skytree.jp')
ON CONFLICT DO NOTHING;
